services:
  postgres:
    image: postgres:16
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - /opt/replika/pq:/var/lib/postgresql/data
  redis:
    restart: on-failure
    image: redis:7.2.4-alpine
    volumes:
      - /opt/replika/cache:/data
  replika:
    image: docker.io/clearloop/takeover:latest
    restart: on-failure
    command: ["-c", "/etc/replika/replika.toml", "-v"]
    depends_on:
      - postgres
      - redis
    volumes:
      - /opt/replika/etc/:/etc/replika
    ports:
      - 5888:4000
    links:
      - postgres
      - redis
