services:
  postgres:
    image: postgres:16
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - /etc/takeover/pq:/var/lib/postgresql/data
  redis:
    restart: on-failure
    image: redis:7.2.4-alpine
    volumes:
      - /etc/takeover/cache:/data
  replika:
    image: docker.io/clearloop/takeover:latest
    restart: on-failure
    command: ["-c", "/etc/config/config.toml", "-v"]
    depends_on:
      - postgres
      - redis
    volumes:
      - /home/ec2-user/takeover:/etc/config
    ports:
      - 5888:4000
    links:
      - postgres
      - redis
